# Generated by Django 4.1.13 on 2024-06-12 13:19

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', tinymce.models.HTMLField()),
                ('picture', models.ImageField(upload_to='AboutMe/')),
            ],
        ),
        migrations.CreateModel(
            name='HomeBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hello', models.CharField(max_length=100)),
                ('who_am_i', models.CharField(max_length=200)),
                ('education', models.CharField(max_length=200)),
                ('picture', models.ImageField(default='home-right.png', upload_to='HomeBanner/')),
                ('cv_button', models.CharField(max_length=50)),
                ('cv_file', models.FileField(upload_to='cv/')),
                ('contact_me_button', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'greeting',
            },
        ),
    ]
